# Generated by Django 2.2.4 on 2020-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
