# Generated by Django 2.2.4 on 2020-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
